<?xml version="1.0"?>
<robot name="differential_wheeled_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:include filename="$(find betsy_setup)/urdf/wheel.urdf.xacro" /> 


<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>


  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>



  <!-- DECLARATION DES PROPRIETES -->
  <!-- ////////////////////////// -->
   
  
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />
  <property name="M_PI_2" value="1.570796327" /> 
  <property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body -->
  
  <property name="base_height" value="0.5" /> 
  <property name="base_mass" value="5" /> <!-- in kg-->
  
  <property name="base_width" value="0.40" />
  <property name="base_length" value="0.55" /> 
  
  <property name="base_radius" value="0.15" /> 


  <!-- caster wheel radius and height -->
  <!-- caster wheel mass -->
  <property name="caster_l_height" value="0.0" /> 
  <property name="caster_l_radius" value="0.07" /> 
  <property name="caster_l_mass" value="0.5" /> <!-- in kg-->



  <!-- caster wheel radius and height -->
  <!-- caster wheel mass -->
  <property name="caster_r_height" value="0.0" /> 
  <property name="caster_r_radius" value="0.07" /> 
  <property name="caster_r_mass" value="0.5" /> <!-- in kg-->


<!-- Main body triangle dimensions -->
  <property name="base_t_mass" value="2" /> <!-- in kg-->
  <property name="triangle_length" value="0.3" />
  <property name="triangle_width" value="0.3" />
  <property name="triangle_height" value="0.1" />


  
<!-- Calcul de l'inertie -->
  
  
  <!-- Macro for calculating inertia of cube -->
  <macro name="box_inertia" params="m h w l">
    <inertia  ixx="${m*(h*h+l*l)/12}" ixy = "0" ixz = "0"
              iyy="${m*(w*w+l*l)/12}" iyz = "0"
              izz="${m*(w*w+h*h)/12}" /> 
  </macro>
  
  
    <!-- Macro for calculating inertia of cylinder -->
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>

  
  
<!-- DECLARATION DES COMPOSANTES DU MODELE -->
<!-- ///////////////////////////////////// -->
   


<!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0" 
          izz="0.0001" />
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>



<!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <!--The 3x3 rotational inertia matrix. -->
        <box_inertia  m="${base_mass}" h="${base_height}" w="${base_width}" l="${base_length}" />

    </inertial>    
    <visual>
      <origin xyz="-0.2 0 0.15" rpy="0 0 0" />
      <geometry>


          <box size= "${base_length} ${base_width} ${base_height}" />

      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>

          <box size= "${base_length} ${base_width} ${base_height}" />

      </geometry>
    </collision>     
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  

  <!-- BASE-triangle -->
 
  <link name="base_triangle">
    <inertial>
      <mass value="${base_t_mass}" />
      <origin xyz="0 0 0" />
      
        <box_inertia  m="${base_mass}" h="${base_height}" w="${base_width}" l="${base_length}" />

    </inertial>    
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>

          <box size= "${triangle_length} ${triangle_width} ${triangle_height}" />

      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>

          <box size= "${triangle_length} ${triangle_width} ${triangle_height}" />

      </geometry>
    </collision>     
  </link>

  <joint name="base_triangle" type="fixed">
      <parent link="base_link"/>
      <child link="base_triangle"/>
      <origin xyz="${triangle_length/2} 0 ${triangle_height/2 - 0.05}" rpy="0 0 0"/>
    </joint>

  <gazebo reference="base_triangle">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>



<!--Caster left  -->

<link name="caster_left_link">

    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
	<sphere radius="${caster_l_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  

      <collision>
        <geometry>

	<sphere radius="${caster_l_radius}" />

        </geometry>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      </collision>      
      <inertial>
        <mass value="${caster_l_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" 
                 izz="0.001" />
      </inertial>
    </link>

 <joint name="caster_left_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_left_link"/>
      <origin xyz="-${base_length-0.09} ${base_width/2 - 0.06} -${caster_r_radius/2 + 0.15}" rpy="${-M_PI/2} 0 0"/>
    </joint>


  <gazebo reference="caster_left_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
 


<!--Caster right  -->

    <link name="caster_right_link">

    <visual>
      <origin xyz="0.00 0.00 0 " rpy="${M_PI/2} 0 0" /> 

      <geometry>


	<sphere radius="${caster_r_radius}" />


      </geometry>
      <material name="Black" />
    </visual>  



      <collision>
        <geometry>
		<sphere radius="${caster_r_radius}" />
        </geometry>
      <origin xyz="0 0 0 " rpy="${M_PI/2} 0 0" /> 
      </collision>      
      <inertial>
        <mass value="${caster_r_mass}" />
        <origin xyz="0 0 0" />        
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" 
                 izz="0.001" />
      </inertial>
    </link>

    <joint name="caster_right_joint" type="fixed">
      <parent link="base_link"/>
      <child link="caster_right_link"/>
      <origin xyz="-${base_length-0.09} ${-base_width/2 + 0.06} -${caster_r_radius/2 + 0.15}" rpy="${-M_PI/2} 0 0"/>
    </joint>


  <gazebo reference="caster_right_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  






  <!-- Wheels -->

  <property name="wheel_mass" value="2.5" /> --> <!-- in kg-->
  
  <property name="base_x_origin_to_wheel_origin" value="0.0" />
  <property name="base_y_origin_to_wheel_origin" value="0.3" />
  <property name="base_z_origin_to_wheel_origin" value="-0.15" />


  <!-- Hokuyo Laser scanner -->
  <property name="hokuyo_size" value="0.05" />



  


<!-- Wheel Definitions -->

  <wheel fb="front" lr="right" parent="base_link" translateX="0" translateY="0.5" flipY="1"/>
  <wheel fb="front" lr="left" parent="base_link" translateX="0" translateY="-0.5" flipY="1"/>
	 
  <!-- SENSORS -->
  
  <!-- hokuyo -->

  <link name="hokuyo_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
      </geometry>
      <material name="Blue" />
    </visual>
  </link>
  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="${base_radius - hokuyo_size/2 + 0.20} 0 ${triangle_height/2 + 0.03}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="hokuyo_link" />
  </joint>
  <gazebo reference="hokuyo_link">
    <material>Gazebo/Blue</material>
    <turnGravityOff>false</turnGravityOff>
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>${hokuyo_size/2} 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>10.0</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
  
  
  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>front_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_footprint</robotBaseFrame>


    </plugin>
  </gazebo> 




</robot>
